/**:
  ros__parameters:
    calibration_file: $(find-pkg-share nebula_decoders)/calibration/velodyne/$(var sensor_model).yaml
    setup_sensor: true
    advanced_diagnostics: false
    launch_hw: true
    sensor_model: VLP16
    return_mode: Dual
    gnss_port: 2369
    min_range: 0.3
    max_range: 300
    packet_mtu_size: 1500
    rotation_speed: 600
    cloud_min_angle: 0
    cloud_max_angle: 360
    diag_span: 1000
    scan_phase: 0
    host_ip: "255.255.255.255"
    sensor_ip: "192.168.1.201"
    data_port: 2368
    frame_id: data_link