/**:
  ros__parameters:
    host_ip: "255.255.255.255"
    sensor_ip: "192.168.1.201"
    data_port: 2368
    frame_id: data_link
    diag_span: 1000
    scan_phase: 0.0
    setup_sensor: true
    sensor_model: Helios
    return_mode: Dual
    gnss_port: 2369
    packet_mtu_size: 1500
    cloud_min_angle: 0
    cloud_max_angle: 360
    dual_return_distance_threshold: 0.1
