/**:
  ros__parameters:
    calibration_file: "$(find-pkg-share nebula_decoders)/calibration/velodyne/VLP32.yaml"
    setup_sensor: true
    diag_span: 1000
    advanced_diagnostics: false
    launch_hw: false
    sensor_model: "VLP32"
    return_mode: "Dual"
    host_ip: "255.255.255.255"
    sensor_ip: "192.168.1.201"
    data_port: 2368
    gnss_port: 2369
    frame_id: velodyne
    scan_phase: 1.0
    min_range: 3.
    max_range: 300.
    packet_mtu_size: 1500
    rotation_speed: 360
    cloud_min_angle: 0
    cloud_max_angle: 360
